stopwords_hashset = {'feel', 'problem', 'thing', 'think', 'sleep',  'pain', 'hear', 'symptom', 'change', 'attack',
                     'heart', 'panic', 'walk', 'move', 'fall', 'increase', 'panic attack', 'scar', 'sit', 'strong',
                     'cold', 'thought', 'face', 'fear', 'slow', 'eye', 'speak', 'cry', 'quick', 'breathe', 'feeling',
                     'hear feel thing', 'mental', 'mood', 'shake', 'breath', 'skin', 'headache', 'dream', 'heal',
                     'sweat', 'force',  'feel will happen', 'double',  'emotional', 'tear', 'seizure', 'sensation',
                     'balance', 'swell', 'tooth', 'clinic', 'concentrate', 'nightmare', 'syndrome', 'remember', 'nose',
                     'pregnant','cramp', 'unusual', 'swallow', 'scream', 'injury', 'joint', 'ang', 'difficulty',
                     'tingle', 'pulse', 'taste', 'gas', 'color', 'tongue',  'chill', 'flush', 'frequent', 'movement',
                     'scale',   'heartbeat',  'twitch', 'tumor', 'lump', 'feel surroundings real', 'urine', 'gum',
                     'pain jaw neck', 'confusion', 'suicide',  'bloat', 'problem vision hear', 'trauma', 'stool',
                     'twist', 'overdose', 'discharge', 'choke', 'concentration', 'bruise', 'heartburn', 'coma',
                     'object', 'stiffness', 'nasal', 'sneeze', 'hung', 'gag', 'rapidly change mood',
                     'doctor side effect', 'menstrual'}